using UnityEngine;

/// <summary>
/// Baked motion of the source rig's weapon socket bone (ik_hand_gun), sampled
/// from the Grruzam clips and pre-converted into the Hero's right-hand local
/// frame. Humanoid retargeting drops non-humanoid bones, so without this the
/// sword rigidly follows the hand and loses the authored blade motion.
/// Values are already in Hero-hand local space — the socket applies them
/// directly. Generated by Tools &gt; Project Restart &gt; Bake Weapon Bone Motion.
/// </summary>
public sealed class WeaponMotionSet : ScriptableObject
{
    [System.Serializable]
    public struct Key
    {
        public float t;          // normalized clip time 0..1
        public Vector3 pos;      // local pos relative to Hero hand bone
        public Quaternion rot;   // local rot relative to Hero hand bone
    }

    [System.Serializable]
    public sealed class Entry
    {
        public string clipName;
        public Key[] keys;
    }

    [Tooltip("Static socket transform (bind pose) in Hero-hand local space — used when the playing clip has no baked curve.")]
    public Vector3 bindPos;
    public Quaternion bindRot = Quaternion.identity;

    public Entry[] entries = new Entry[0];

    public Entry Find(string clipName)
    {
        if (string.IsNullOrEmpty(clipName)) return null;
        foreach (var e in entries)
            if (e != null && e.clipName == clipName) return e;
        return null;
    }

    /// <summary>Sample an entry at normalized time, clamped. Falls back to bind.</summary>
    public void Sample(Entry e, float normalizedTime, out Vector3 pos, out Quaternion rot)
    {
        if (e == null || e.keys == null || e.keys.Length == 0)
        {
            pos = bindPos;
            rot = bindRot;
            return;
        }
        var keys = e.keys;
        var t = Mathf.Clamp01(normalizedTime);
        if (t <= keys[0].t) { pos = keys[0].pos; rot = keys[0].rot; return; }
        var last = keys[keys.Length - 1];
        if (t >= last.t) { pos = last.pos; rot = last.rot; return; }
        for (var i = 1; i < keys.Length; i++)
        {
            if (t > keys[i].t) continue;
            var a = keys[i - 1];
            var b = keys[i];
            var k = Mathf.Approximately(b.t, a.t) ? 0f : (t - a.t) / (b.t - a.t);
            pos = Vector3.LerpUnclamped(a.pos, b.pos, k);
            rot = Quaternion.SlerpUnclamped(a.rot, b.rot, k);
            return;
        }
        pos = last.pos;
        rot = last.rot;
    }
}
